//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for applicationPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="applicationPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="personNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="personName" type="{http://webservice.flhk.com/FLHKWebService/1.0}personName" minOccurs="0"/>
 *         &lt;element name="ssn" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://webservice.flhk.com/FLHKWebService/1.0}genderEnum" minOccurs="0"/>
 *         &lt;element name="earnedIncome" type="{http://webservice.flhk.com/FLHKWebService/1.0}earnedIncome" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="unearnedIncome" type="{http://webservice.flhk.com/FLHKWebService/1.0}unearnedIncome" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="positionOnApp" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="applicantRemoved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="applicantRemovedReason" type="{http://webservice.flhk.com/FLHKWebService/1.0}applicantRemovedReasonEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "applicationPerson", propOrder = {
    "personNumber",
    "personName",
    "ssn",
    "dateOfBirth",
    "gender",
    "earnedIncome",
    "unearnedIncome",
    "positionOnApp",
    "applicantRemoved",
    "applicantRemovedReason"
})
@XmlSeeAlso({
    ApplicationOther.class,
    ApplicationParent.class,
    ApplicationChild.class
})
public abstract class ApplicationPerson {

    protected Long personNumber;
    protected PersonName personName;
    protected String ssn;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfBirth;
    protected GenderEnum gender;
    @XmlElement(nillable = true)
    protected List<EarnedIncome> earnedIncome;
    @XmlElement(nillable = true)
    protected List<UnearnedIncome> unearnedIncome;
    protected Integer positionOnApp;
    protected Boolean applicantRemoved;
    protected ApplicantRemovedReasonEnum applicantRemovedReason;

    /**
     * Gets the value of the personNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPersonNumber() {
        return personNumber;
    }

    /**
     * Sets the value of the personNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPersonNumber(Long value) {
        this.personNumber = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setPersonName(PersonName value) {
        this.personName = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderEnum }
     *     
     */
    public GenderEnum getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderEnum }
     *     
     */
    public void setGender(GenderEnum value) {
        this.gender = value;
    }

    /**
     * Gets the value of the earnedIncome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the earnedIncome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEarnedIncome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EarnedIncome }
     * 
     * 
     */
    public List<EarnedIncome> getEarnedIncome() {
        if (earnedIncome == null) {
            earnedIncome = new ArrayList<EarnedIncome>();
        }
        return this.earnedIncome;
    }

    /**
     * Gets the value of the unearnedIncome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unearnedIncome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnearnedIncome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnearnedIncome }
     * 
     * 
     */
    public List<UnearnedIncome> getUnearnedIncome() {
        if (unearnedIncome == null) {
            unearnedIncome = new ArrayList<UnearnedIncome>();
        }
        return this.unearnedIncome;
    }

    /**
     * Gets the value of the positionOnApp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPositionOnApp() {
        return positionOnApp;
    }

    /**
     * Sets the value of the positionOnApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPositionOnApp(Integer value) {
        this.positionOnApp = value;
    }

    /**
     * Gets the value of the applicantRemoved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplicantRemoved() {
        return applicantRemoved;
    }

    /**
     * Sets the value of the applicantRemoved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplicantRemoved(Boolean value) {
        this.applicantRemoved = value;
    }

    /**
     * Gets the value of the applicantRemovedReason property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantRemovedReasonEnum }
     *     
     */
    public ApplicantRemovedReasonEnum getApplicantRemovedReason() {
        return applicantRemovedReason;
    }

    /**
     * Sets the value of the applicantRemovedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantRemovedReasonEnum }
     *     
     */
    public void setApplicantRemovedReason(ApplicantRemovedReasonEnum value) {
        this.applicantRemovedReason = value;
    }

}
