//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for applicationOther complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="applicationOther">
 *   &lt;complexContent>
 *     &lt;extension base="{http://webservice.flhk.com/FLHKWebService/1.0}applicationPerson">
 *       &lt;sequence>
 *         &lt;element name="householdCareExpense" type="{http://webservice.flhk.com/FLHKWebService/1.0}householdCareExpense" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="childSupportExpenseMonthlyAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="childSupportExpenseNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="childSupportExpenseStatus" type="{http://webservice.flhk.com/FLHKWebService/1.0}expenseStatusEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "applicationOther", propOrder = {
    "householdCareExpense",
    "childSupportExpenseMonthlyAmount",
    "childSupportExpenseNumber",
    "childSupportExpenseStatus"
})
public class ApplicationOther
    extends ApplicationPerson
{

    @XmlElement(nillable = true)
    protected List<HouseholdCareExpense> householdCareExpense;
    protected BigDecimal childSupportExpenseMonthlyAmount;
    protected Long childSupportExpenseNumber;
    protected FinanceItemStatusEnum childSupportExpenseStatus;

    /**
     * Gets the value of the householdCareExpense property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the householdCareExpense property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHouseholdCareExpense().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HouseholdCareExpense }
     * 
     * 
     */
    public List<HouseholdCareExpense> getHouseholdCareExpense() {
        if (householdCareExpense == null) {
            householdCareExpense = new ArrayList<HouseholdCareExpense>();
        }
        return this.householdCareExpense;
    }

    /**
     * Gets the value of the childSupportExpenseMonthlyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChildSupportExpenseMonthlyAmount() {
        return childSupportExpenseMonthlyAmount;
    }

    /**
     * Sets the value of the childSupportExpenseMonthlyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChildSupportExpenseMonthlyAmount(BigDecimal value) {
        this.childSupportExpenseMonthlyAmount = value;
    }

    /**
     * Gets the value of the childSupportExpenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChildSupportExpenseNumber() {
        return childSupportExpenseNumber;
    }

    /**
     * Sets the value of the childSupportExpenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChildSupportExpenseNumber(Long value) {
        this.childSupportExpenseNumber = value;
    }

    /**
     * Gets the value of the childSupportExpenseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public FinanceItemStatusEnum getChildSupportExpenseStatus() {
        return childSupportExpenseStatus;
    }

    /**
     * Sets the value of the childSupportExpenseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public void setChildSupportExpenseStatus(FinanceItemStatusEnum value) {
        this.childSupportExpenseStatus = value;
    }

}
