//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for childParentMemberBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childParentMemberBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://webservice.flhk.com/FLHKWebService/1.0}member">
 *       &lt;sequence>
 *         &lt;element name="workPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="memberMissingInfo" type="{http://webservice.flhk.com/FLHKWebService/1.0}memberMissingInfo" minOccurs="0"/>
 *         &lt;element name="incomeMissingInfo" type="{http://webservice.flhk.com/FLHKWebService/1.0}incomeMissingInfo" minOccurs="0"/>
 *         &lt;element name="expenseMissingInfo" type="{http://webservice.flhk.com/FLHKWebService/1.0}expenseMissingInfo" minOccurs="0"/>
 *         &lt;element name="fullTimeStudentIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childParentMemberBase", propOrder = {
    "workPhone",
    "memberMissingInfo",
    "incomeMissingInfo",
    "expenseMissingInfo",
    "fullTimeStudentIndicator"
})
@XmlSeeAlso({
    ParentMember.class,
    ChildMember.class
})
public abstract class ChildParentMemberBase
    extends Member
{

    protected String workPhone;
    protected MemberMissingInfo memberMissingInfo;
    protected IncomeMissingInfo incomeMissingInfo;
    protected ExpenseMissingInfo expenseMissingInfo;
    protected Boolean fullTimeStudentIndicator;

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhone(String value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the memberMissingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MemberMissingInfo }
     *     
     */
    public MemberMissingInfo getMemberMissingInfo() {
        return memberMissingInfo;
    }

    /**
     * Sets the value of the memberMissingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberMissingInfo }
     *     
     */
    public void setMemberMissingInfo(MemberMissingInfo value) {
        this.memberMissingInfo = value;
    }

    /**
     * Gets the value of the incomeMissingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IncomeMissingInfo }
     *     
     */
    public IncomeMissingInfo getIncomeMissingInfo() {
        return incomeMissingInfo;
    }

    /**
     * Sets the value of the incomeMissingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncomeMissingInfo }
     *     
     */
    public void setIncomeMissingInfo(IncomeMissingInfo value) {
        this.incomeMissingInfo = value;
    }

    /**
     * Gets the value of the expenseMissingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExpenseMissingInfo }
     *     
     */
    public ExpenseMissingInfo getExpenseMissingInfo() {
        return expenseMissingInfo;
    }

    /**
     * Sets the value of the expenseMissingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpenseMissingInfo }
     *     
     */
    public void setExpenseMissingInfo(ExpenseMissingInfo value) {
        this.expenseMissingInfo = value;
    }

    /**
     * Gets the value of the fullTimeStudentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFullTimeStudentIndicator() {
        return fullTimeStudentIndicator;
    }

    /**
     * Sets the value of the fullTimeStudentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFullTimeStudentIndicator(Boolean value) {
        this.fullTimeStudentIndicator = value;
    }

}
