//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expense">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="expenseStatus" type="{http://webservice.flhk.com/FLHKWebService/1.0}financeItemStatusEnum"/>
 *         &lt;element name="nameOfCaredForPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reportedMonthlyAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="type" type="{http://webservice.flhk.com/FLHKWebService/1.0}expenseTypeEnum"/>
 *         &lt;element name="jpaVersion" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expense", propOrder = {
    "expenseNumber",
    "expenseStatus",
    "nameOfCaredForPerson",
    "reportedMonthlyAmount",
    "type",
    "jpaVersion"
})
public class Expense {

    protected Long expenseNumber;
    @XmlElement(required = true)
    protected FinanceItemStatusEnum expenseStatus;
    protected String nameOfCaredForPerson;
    @XmlElement(required = true)
    protected BigDecimal reportedMonthlyAmount;
    @XmlElement(required = true)
    protected ExpenseTypeEnum type;
    protected Long jpaVersion;

    /**
     * Gets the value of the expenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExpenseNumber() {
        return expenseNumber;
    }

    /**
     * Sets the value of the expenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExpenseNumber(Long value) {
        this.expenseNumber = value;
    }

    /**
     * Gets the value of the expenseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public FinanceItemStatusEnum getExpenseStatus() {
        return expenseStatus;
    }

    /**
     * Sets the value of the expenseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public void setExpenseStatus(FinanceItemStatusEnum value) {
        this.expenseStatus = value;
    }

    /**
     * Gets the value of the nameOfCaredForPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfCaredForPerson() {
        return nameOfCaredForPerson;
    }

    /**
     * Sets the value of the nameOfCaredForPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfCaredForPerson(String value) {
        this.nameOfCaredForPerson = value;
    }

    /**
     * Gets the value of the reportedMonthlyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReportedMonthlyAmount() {
        return reportedMonthlyAmount;
    }

    /**
     * Sets the value of the reportedMonthlyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReportedMonthlyAmount(BigDecimal value) {
        this.reportedMonthlyAmount = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ExpenseTypeEnum }
     *     
     */
    public ExpenseTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpenseTypeEnum }
     *     
     */
    public void setType(ExpenseTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the jpaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJpaVersion() {
        return jpaVersion;
    }

    /**
     * Sets the value of the jpaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJpaVersion(Long value) {
        this.jpaVersion = value;
    }

}
