//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for healthPlan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="healthPlan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="healthPlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="healthPlanEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="healthPlanPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="healthPlanWebSite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "healthPlan", propOrder = {
    "healthPlan",
    "healthPlanEmail",
    "healthPlanPhoneNumber",
    "healthPlanWebSite"
})
public class HealthPlan {

    protected String healthPlan;
    protected String healthPlanEmail;
    protected String healthPlanPhoneNumber;
    protected String healthPlanWebSite;

    /**
     * Gets the value of the healthPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthPlan() {
        return healthPlan;
    }

    /**
     * Sets the value of the healthPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthPlan(String value) {
        this.healthPlan = value;
    }

    /**
     * Gets the value of the healthPlanEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthPlanEmail() {
        return healthPlanEmail;
    }

    /**
     * Sets the value of the healthPlanEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthPlanEmail(String value) {
        this.healthPlanEmail = value;
    }

    /**
     * Gets the value of the healthPlanPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthPlanPhoneNumber() {
        return healthPlanPhoneNumber;
    }

    /**
     * Sets the value of the healthPlanPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthPlanPhoneNumber(String value) {
        this.healthPlanPhoneNumber = value;
    }

    /**
     * Gets the value of the healthPlanWebSite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthPlanWebSite() {
        return healthPlanWebSite;
    }

    /**
     * Sets the value of the healthPlanWebSite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthPlanWebSite(String value) {
        this.healthPlanWebSite = value;
    }

}
