//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for householdCareExpense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="householdCareExpense">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expenseNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="expenseStatus" type="{http://webservice.flhk.com/FLHKWebService/1.0}expenseStatusEnum" minOccurs="0"/>
 *         &lt;element name="monthlyAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="nameOfCaredForPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "householdCareExpense", propOrder = {
    "expenseNumber",
    "expenseStatus",
    "monthlyAmount",
    "nameOfCaredForPerson"
})
public class HouseholdCareExpense {

    protected Long expenseNumber;
    protected FinanceItemStatusEnum expenseStatus;
    protected BigDecimal monthlyAmount;
    protected String nameOfCaredForPerson;

    /**
     * Gets the value of the expenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExpenseNumber() {
        return expenseNumber;
    }

    /**
     * Sets the value of the expenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExpenseNumber(Long value) {
        this.expenseNumber = value;
    }

    /**
     * Gets the value of the expenseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public FinanceItemStatusEnum getExpenseStatus() {
        return expenseStatus;
    }

    /**
     * Sets the value of the expenseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinanceItemStatusEnum }
     *     
     */
    public void setExpenseStatus(FinanceItemStatusEnum value) {
        this.expenseStatus = value;
    }

    /**
     * Gets the value of the monthlyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyAmount() {
        return monthlyAmount;
    }

    /**
     * Sets the value of the monthlyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyAmount(BigDecimal value) {
        this.monthlyAmount = value;
    }

    /**
     * Gets the value of the nameOfCaredForPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfCaredForPerson() {
        return nameOfCaredForPerson;
    }

    /**
     * Sets the value of the nameOfCaredForPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfCaredForPerson(String value) {
        this.nameOfCaredForPerson = value;
    }

}
