//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incomeSubTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="incomeSubTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EMPLOYMENT"/>
 *     &lt;enumeration value="SELF_EMPLOYMENT"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="CHILD_SUPPORT"/>
 *     &lt;enumeration value="VA_BENEFITS"/>
 *     &lt;enumeration value="SOCIAL_SECURITY"/>
 *     &lt;enumeration value="SSI"/>
 *     &lt;enumeration value="UNEMPLOYMENT"/>
 *     &lt;enumeration value="WORKERS_COMP"/>
 *     &lt;enumeration value="INVESTMENT"/>
 *     &lt;enumeration value="PENSION"/>
 *     &lt;enumeration value="DISABILITY"/>
 *     &lt;enumeration value="OTHER_UNEARNED"/>
 *     &lt;enumeration value="OTHER_EARNED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "incomeSubTypeEnum")
@XmlEnum
public enum IncomeSubTypeEnum {

    EMPLOYMENT,
    SELF_EMPLOYMENT,
    OTHER,
    CHILD_SUPPORT,
    VA_BENEFITS,
    SOCIAL_SECURITY,
    SSI,
    UNEMPLOYMENT,
    WORKERS_COMP,
    INVESTMENT,
    PENSION,
    DISABILITY,
    OTHER_UNEARNED,
    OTHER_EARNED;

    public String value() {
        return name();
    }

    public static IncomeSubTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
