//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for insuranceProviderEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="insuranceProviderEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MEDICAID"/>
 *     &lt;enumeration value="MEDICARE"/>
 *     &lt;enumeration value="TRI_CARE"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "insuranceProviderEnum")
@XmlEnum
public enum InsuranceProviderEnum {

    MEDICAID,
    MEDICARE,
    TRI_CARE,
    OTHER;

    public String value() {
        return name();
    }

    public static InsuranceProviderEnum fromValue(String v) {
        return valueOf(v);
    }

}
