//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 12:34:02 PM IST 
//


package com.flhk.webservice.flhkwebservice._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parentMember complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parentMember">
 *   &lt;complexContent>
 *     &lt;extension base="{http://webservice.flhk.com/FLHKWebService/1.0}childParentMemberBase">
 *       &lt;sequence>
 *         &lt;element name="parentType" type="{http://webservice.flhk.com/FLHKWebService/1.0}parentTypeEnum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parentMember", propOrder = {
    "parentType"
})
public class ParentMember
    extends ChildParentMemberBase
{

    @XmlElement(required = true)
    protected ParentTypeEnum parentType;

    /**
     * Gets the value of the parentType property.
     * 
     * @return
     *     possible object is
     *     {@link ParentTypeEnum }
     *     
     */
    public ParentTypeEnum getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentTypeEnum }
     *     
     */
    public void setParentType(ParentTypeEnum value) {
        this.parentType = value;
    }

}
