//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.05 at 12:55:55 PM CST 
//


package com.psi.vida.services.email._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.flhk.webservice.service._1.ServiceReply;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.psi.vida.services.email._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("http://services.vida.psi.com/email/1.0", "email");
    private final static QName _SendEmailResponse_QNAME = new QName("http://services.vida.psi.com/email/1.0", "SendEmailResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.psi.vida.services.email._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link SendEmail }
     * 
     */
    public SendEmail createSendEmail() {
        return new SendEmail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/email/1.0", name = "email")
    public JAXBElement<EmailType> createEmail(EmailType value) {
        return new JAXBElement<EmailType>(_Email_QNAME, EmailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceReply }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/email/1.0", name = "SendEmailResponse")
    public JAXBElement<ServiceReply> createSendEmailResponse(ServiceReply value) {
        return new JAXBElement<ServiceReply>(_SendEmailResponse_QNAME, ServiceReply.class, null, value);
    }

}
