//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 11:47:16 AM CST 
//


package com.psi.vida.services.clientmanagement._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for applicant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="applicant"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="applicantEmployers" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="applicantEmployer" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantEmployer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="applicantExpenses" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="applicantExpense" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantExpense" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="applicantIncomes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="applicantIncome" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantIncome" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="applicantRenewalRemovedReason" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantRenewalRemovedReasonEnum" minOccurs="0"/&gt;
 *         &lt;element name="applicationPersonId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="applyingForKidCare" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="atoRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="atoReferralId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="blindOrDisabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="caretaker" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="citizenOfUS" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="citizenshipFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}citizenshipFactors" minOccurs="0"/&gt;
 *         &lt;element name="claimedByAtoRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cmsPreapproved" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="dateOfBirth" type="{http://services.vida.psi.com/ClientManagement/1.0}calendarDay" minOccurs="0"/&gt;
 *         &lt;element name="employmentFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}employmentFactors" minOccurs="0"/&gt;
 *         &lt;element name="fosterCare" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="fullTimeStudent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="gender" type="{http://services.vida.psi.com/ClientManagement/1.0}genderEnum" minOccurs="0"/&gt;
 *         &lt;element name="identityFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}identityFactors" minOccurs="0"/&gt;
 *         &lt;element name="immigrationFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}immigrationFactors" minOccurs="0"/&gt;
 *         &lt;element name="incarcerated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="insuranceInfo" type="{http://services.vida.psi.com/ClientManagement/1.0}insuranceInfo" minOccurs="0"/&gt;
 *         &lt;element name="jpaVersion" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="limitedInAnyWay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="livesWithPrimaryContact" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="medicaidEligibilityEndDate" type="{http://services.vida.psi.com/ClientManagement/1.0}calendarDay" minOccurs="0"/&gt;
 *         &lt;element name="medicaidRecipientId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="needsSpecialTherapy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="numberOfBabiesDue" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="parentType" type="{http://services.vida.psi.com/ClientManagement/1.0}parentTypeEnum" minOccurs="0"/&gt;
 *         &lt;element name="personName" type="{http://services.vida.psi.com/ClientManagement/1.0}personName" minOccurs="0"/&gt;
 *         &lt;element name="personNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="positionOnApp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="pregnant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="race1" type="{http://services.vida.psi.com/ClientManagement/1.0}raceEnum" minOccurs="0"/&gt;
 *         &lt;element name="race2" type="{http://services.vida.psi.com/ClientManagement/1.0}raceEnum" minOccurs="0"/&gt;
 *         &lt;element name="raceHispanic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="spouseTaxFilerAtoRefId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ssnAppliedDate" type="{http://services.vida.psi.com/ClientManagement/1.0}calendarDay" minOccurs="0"/&gt;
 *         &lt;element name="stricken" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="taxationFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}taxationFactors" minOccurs="0"/&gt;
 *         &lt;element name="tribalFactors" type="{http://services.vida.psi.com/ClientManagement/1.0}tribalFactors" minOccurs="0"/&gt;
 *         &lt;element name="unpaidMedicalBillsIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="usEntryDate" type="{http://services.vida.psi.com/ClientManagement/1.0}calendarDay" minOccurs="0"/&gt;
 *         &lt;element name="uscisNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="usesMoreMedicalCareThanUsual" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="veteranStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="workPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "applicant", propOrder = {
    "applicantEmployers",
    "applicantExpenses",
    "applicantIncomes",
    "applicantRenewalRemovedReason",
    "applicationPersonId",
    "applyingForKidCare",
    "atoRefId",
    "atoReferralId",
    "blindOrDisabled",
    "caretaker",
    "citizenOfUS",
    "citizenshipFactors",
    "claimedByAtoRefId",
    "cmsPreapproved",
    "dateOfBirth",
    "employmentFactors",
    "fosterCare",
    "fullTimeStudent",
    "gender",
    "identityFactors",
    "immigrationFactors",
    "incarcerated",
    "insuranceInfo",
    "jpaVersion",
    "limitedInAnyWay",
    "livesWithPrimaryContact",
    "medicaidEligibilityEndDate",
    "medicaidRecipientId",
    "needsSpecialTherapy",
    "numberOfBabiesDue",
    "parentType",
    "personName",
    "personNumber",
    "positionOnApp",
    "pregnant",
    "race1",
    "race2",
    "raceHispanic",
    "spouseTaxFilerAtoRefId",
    "ssn",
    "ssnAppliedDate",
    "stricken",
    "taxationFactors",
    "tribalFactors",
    "unpaidMedicalBillsIndicator",
    "usEntryDate",
    "uscisNumber",
    "usesMoreMedicalCareThanUsual",
    "veteranStatus",
    "workPhone"
})
public class Applicant {

    protected Applicant.ApplicantEmployers applicantEmployers;
    protected Applicant.ApplicantExpenses applicantExpenses;
    protected Applicant.ApplicantIncomes applicantIncomes;
    @XmlSchemaType(name = "string")
    protected ApplicantRenewalRemovedReasonEnum applicantRenewalRemovedReason;
    protected Long applicationPersonId;
    protected Boolean applyingForKidCare;
    protected String atoRefId;
    protected String atoReferralId;
    protected Boolean blindOrDisabled;
    protected Boolean caretaker;
    protected Boolean citizenOfUS;
    protected CitizenshipFactors citizenshipFactors;
    protected String claimedByAtoRefId;
    protected boolean cmsPreapproved;
    protected CalendarDay dateOfBirth;
    protected EmploymentFactors employmentFactors;
    protected Boolean fosterCare;
    protected Boolean fullTimeStudent;
    @XmlSchemaType(name = "string")
    protected GenderEnum gender;
    protected IdentityFactors identityFactors;
    protected ImmigrationFactors immigrationFactors;
    protected Boolean incarcerated;
    protected InsuranceInfo insuranceInfo;
    protected Long jpaVersion;
    protected Boolean limitedInAnyWay;
    protected Boolean livesWithPrimaryContact;
    protected CalendarDay medicaidEligibilityEndDate;
    protected String medicaidRecipientId;
    protected Boolean needsSpecialTherapy;
    protected Integer numberOfBabiesDue;
    @XmlSchemaType(name = "string")
    protected ParentTypeEnum parentType;
    protected PersonName personName;
    protected Long personNumber;
    protected Integer positionOnApp;
    protected Boolean pregnant;
    @XmlSchemaType(name = "string")
    protected RaceEnum race1;
    @XmlSchemaType(name = "string")
    protected RaceEnum race2;
    protected Boolean raceHispanic;
    protected String spouseTaxFilerAtoRefId;
    protected String ssn;
    protected CalendarDay ssnAppliedDate;
    protected boolean stricken;
    protected TaxationFactors taxationFactors;
    protected TribalFactors tribalFactors;
    protected Boolean unpaidMedicalBillsIndicator;
    protected CalendarDay usEntryDate;
    protected String uscisNumber;
    protected Boolean usesMoreMedicalCareThanUsual;
    protected Boolean veteranStatus;
    protected String workPhone;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the applicantEmployers property.
     * 
     * @return
     *     possible object is
     *     {@link Applicant.ApplicantEmployers }
     *     
     */
    public Applicant.ApplicantEmployers getApplicantEmployers() {
        return applicantEmployers;
    }

    /**
     * Sets the value of the applicantEmployers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applicant.ApplicantEmployers }
     *     
     */
    public void setApplicantEmployers(Applicant.ApplicantEmployers value) {
        this.applicantEmployers = value;
    }

    /**
     * Gets the value of the applicantExpenses property.
     * 
     * @return
     *     possible object is
     *     {@link Applicant.ApplicantExpenses }
     *     
     */
    public Applicant.ApplicantExpenses getApplicantExpenses() {
        return applicantExpenses;
    }

    /**
     * Sets the value of the applicantExpenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applicant.ApplicantExpenses }
     *     
     */
    public void setApplicantExpenses(Applicant.ApplicantExpenses value) {
        this.applicantExpenses = value;
    }

    /**
     * Gets the value of the applicantIncomes property.
     * 
     * @return
     *     possible object is
     *     {@link Applicant.ApplicantIncomes }
     *     
     */
    public Applicant.ApplicantIncomes getApplicantIncomes() {
        return applicantIncomes;
    }

    /**
     * Sets the value of the applicantIncomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applicant.ApplicantIncomes }
     *     
     */
    public void setApplicantIncomes(Applicant.ApplicantIncomes value) {
        this.applicantIncomes = value;
    }

    /**
     * Gets the value of the applicantRenewalRemovedReason property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantRenewalRemovedReasonEnum }
     *     
     */
    public ApplicantRenewalRemovedReasonEnum getApplicantRenewalRemovedReason() {
        return applicantRenewalRemovedReason;
    }

    /**
     * Sets the value of the applicantRenewalRemovedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantRenewalRemovedReasonEnum }
     *     
     */
    public void setApplicantRenewalRemovedReason(ApplicantRenewalRemovedReasonEnum value) {
        this.applicantRenewalRemovedReason = value;
    }

    /**
     * Gets the value of the applicationPersonId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getApplicationPersonId() {
        return applicationPersonId;
    }

    /**
     * Sets the value of the applicationPersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setApplicationPersonId(Long value) {
        this.applicationPersonId = value;
    }

    /**
     * Gets the value of the applyingForKidCare property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplyingForKidCare() {
        return applyingForKidCare;
    }

    /**
     * Sets the value of the applyingForKidCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplyingForKidCare(Boolean value) {
        this.applyingForKidCare = value;
    }

    /**
     * Gets the value of the atoRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtoRefId() {
        return atoRefId;
    }

    /**
     * Sets the value of the atoRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtoRefId(String value) {
        this.atoRefId = value;
    }

    /**
     * Gets the value of the atoReferralId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtoReferralId() {
        return atoReferralId;
    }

    /**
     * Sets the value of the atoReferralId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtoReferralId(String value) {
        this.atoReferralId = value;
    }

    /**
     * Gets the value of the blindOrDisabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlindOrDisabled() {
        return blindOrDisabled;
    }

    /**
     * Sets the value of the blindOrDisabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlindOrDisabled(Boolean value) {
        this.blindOrDisabled = value;
    }

    /**
     * Gets the value of the caretaker property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCaretaker() {
        return caretaker;
    }

    /**
     * Sets the value of the caretaker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCaretaker(Boolean value) {
        this.caretaker = value;
    }

    /**
     * Gets the value of the citizenOfUS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCitizenOfUS() {
        return citizenOfUS;
    }

    /**
     * Sets the value of the citizenOfUS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCitizenOfUS(Boolean value) {
        this.citizenOfUS = value;
    }

    /**
     * Gets the value of the citizenshipFactors property.
     * 
     * @return
     *     possible object is
     *     {@link CitizenshipFactors }
     *     
     */
    public CitizenshipFactors getCitizenshipFactors() {
        return citizenshipFactors;
    }

    /**
     * Sets the value of the citizenshipFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitizenshipFactors }
     *     
     */
    public void setCitizenshipFactors(CitizenshipFactors value) {
        this.citizenshipFactors = value;
    }

    /**
     * Gets the value of the claimedByAtoRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimedByAtoRefId() {
        return claimedByAtoRefId;
    }

    /**
     * Sets the value of the claimedByAtoRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimedByAtoRefId(String value) {
        this.claimedByAtoRefId = value;
    }

    /**
     * Gets the value of the cmsPreapproved property.
     * 
     */
    public boolean isCmsPreapproved() {
        return cmsPreapproved;
    }

    /**
     * Sets the value of the cmsPreapproved property.
     * 
     */
    public void setCmsPreapproved(boolean value) {
        this.cmsPreapproved = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarDay }
     *     
     */
    public CalendarDay getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarDay }
     *     
     */
    public void setDateOfBirth(CalendarDay value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the employmentFactors property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentFactors }
     *     
     */
    public EmploymentFactors getEmploymentFactors() {
        return employmentFactors;
    }

    /**
     * Sets the value of the employmentFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentFactors }
     *     
     */
    public void setEmploymentFactors(EmploymentFactors value) {
        this.employmentFactors = value;
    }

    /**
     * Gets the value of the fosterCare property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFosterCare() {
        return fosterCare;
    }

    /**
     * Sets the value of the fosterCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFosterCare(Boolean value) {
        this.fosterCare = value;
    }

    /**
     * Gets the value of the fullTimeStudent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFullTimeStudent() {
        return fullTimeStudent;
    }

    /**
     * Sets the value of the fullTimeStudent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFullTimeStudent(Boolean value) {
        this.fullTimeStudent = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderEnum }
     *     
     */
    public GenderEnum getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderEnum }
     *     
     */
    public void setGender(GenderEnum value) {
        this.gender = value;
    }

    /**
     * Gets the value of the identityFactors property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityFactors }
     *     
     */
    public IdentityFactors getIdentityFactors() {
        return identityFactors;
    }

    /**
     * Sets the value of the identityFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityFactors }
     *     
     */
    public void setIdentityFactors(IdentityFactors value) {
        this.identityFactors = value;
    }

    /**
     * Gets the value of the immigrationFactors property.
     * 
     * @return
     *     possible object is
     *     {@link ImmigrationFactors }
     *     
     */
    public ImmigrationFactors getImmigrationFactors() {
        return immigrationFactors;
    }

    /**
     * Sets the value of the immigrationFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmigrationFactors }
     *     
     */
    public void setImmigrationFactors(ImmigrationFactors value) {
        this.immigrationFactors = value;
    }

    /**
     * Gets the value of the incarcerated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncarcerated() {
        return incarcerated;
    }

    /**
     * Sets the value of the incarcerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncarcerated(Boolean value) {
        this.incarcerated = value;
    }

    /**
     * Gets the value of the insuranceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceInfo }
     *     
     */
    public InsuranceInfo getInsuranceInfo() {
        return insuranceInfo;
    }

    /**
     * Sets the value of the insuranceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceInfo }
     *     
     */
    public void setInsuranceInfo(InsuranceInfo value) {
        this.insuranceInfo = value;
    }

    /**
     * Gets the value of the jpaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getJpaVersion() {
        return jpaVersion;
    }

    /**
     * Sets the value of the jpaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setJpaVersion(Long value) {
        this.jpaVersion = value;
    }

    /**
     * Gets the value of the limitedInAnyWay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLimitedInAnyWay() {
        return limitedInAnyWay;
    }

    /**
     * Sets the value of the limitedInAnyWay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLimitedInAnyWay(Boolean value) {
        this.limitedInAnyWay = value;
    }

    /**
     * Gets the value of the livesWithPrimaryContact property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLivesWithPrimaryContact() {
        return livesWithPrimaryContact;
    }

    /**
     * Sets the value of the livesWithPrimaryContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLivesWithPrimaryContact(Boolean value) {
        this.livesWithPrimaryContact = value;
    }

    /**
     * Gets the value of the medicaidEligibilityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarDay }
     *     
     */
    public CalendarDay getMedicaidEligibilityEndDate() {
        return medicaidEligibilityEndDate;
    }

    /**
     * Sets the value of the medicaidEligibilityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarDay }
     *     
     */
    public void setMedicaidEligibilityEndDate(CalendarDay value) {
        this.medicaidEligibilityEndDate = value;
    }

    /**
     * Gets the value of the medicaidRecipientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicaidRecipientId() {
        return medicaidRecipientId;
    }

    /**
     * Sets the value of the medicaidRecipientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicaidRecipientId(String value) {
        this.medicaidRecipientId = value;
    }

    /**
     * Gets the value of the needsSpecialTherapy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNeedsSpecialTherapy() {
        return needsSpecialTherapy;
    }

    /**
     * Sets the value of the needsSpecialTherapy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeedsSpecialTherapy(Boolean value) {
        this.needsSpecialTherapy = value;
    }

    /**
     * Gets the value of the numberOfBabiesDue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfBabiesDue() {
        return numberOfBabiesDue;
    }

    /**
     * Sets the value of the numberOfBabiesDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfBabiesDue(Integer value) {
        this.numberOfBabiesDue = value;
    }

    /**
     * Gets the value of the parentType property.
     * 
     * @return
     *     possible object is
     *     {@link ParentTypeEnum }
     *     
     */
    public ParentTypeEnum getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParentTypeEnum }
     *     
     */
    public void setParentType(ParentTypeEnum value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setPersonName(PersonName value) {
        this.personName = value;
    }

    /**
     * Gets the value of the personNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPersonNumber() {
        return personNumber;
    }

    /**
     * Sets the value of the personNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPersonNumber(Long value) {
        this.personNumber = value;
    }

    /**
     * Gets the value of the positionOnApp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPositionOnApp() {
        return positionOnApp;
    }

    /**
     * Sets the value of the positionOnApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPositionOnApp(Integer value) {
        this.positionOnApp = value;
    }

    /**
     * Gets the value of the pregnant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPregnant() {
        return pregnant;
    }

    /**
     * Sets the value of the pregnant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPregnant(Boolean value) {
        this.pregnant = value;
    }

    /**
     * Gets the value of the race1 property.
     * 
     * @return
     *     possible object is
     *     {@link RaceEnum }
     *     
     */
    public RaceEnum getRace1() {
        return race1;
    }

    /**
     * Sets the value of the race1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceEnum }
     *     
     */
    public void setRace1(RaceEnum value) {
        this.race1 = value;
    }

    /**
     * Gets the value of the race2 property.
     * 
     * @return
     *     possible object is
     *     {@link RaceEnum }
     *     
     */
    public RaceEnum getRace2() {
        return race2;
    }

    /**
     * Sets the value of the race2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaceEnum }
     *     
     */
    public void setRace2(RaceEnum value) {
        this.race2 = value;
    }

    /**
     * Gets the value of the raceHispanic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRaceHispanic() {
        return raceHispanic;
    }

    /**
     * Sets the value of the raceHispanic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRaceHispanic(Boolean value) {
        this.raceHispanic = value;
    }

    /**
     * Gets the value of the spouseTaxFilerAtoRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpouseTaxFilerAtoRefId() {
        return spouseTaxFilerAtoRefId;
    }

    /**
     * Sets the value of the spouseTaxFilerAtoRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpouseTaxFilerAtoRefId(String value) {
        this.spouseTaxFilerAtoRefId = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the ssnAppliedDate property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarDay }
     *     
     */
    public CalendarDay getSsnAppliedDate() {
        return ssnAppliedDate;
    }

    /**
     * Sets the value of the ssnAppliedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarDay }
     *     
     */
    public void setSsnAppliedDate(CalendarDay value) {
        this.ssnAppliedDate = value;
    }

    /**
     * Gets the value of the stricken property.
     * 
     */
    public boolean isStricken() {
        return stricken;
    }

    /**
     * Sets the value of the stricken property.
     * 
     */
    public void setStricken(boolean value) {
        this.stricken = value;
    }

    /**
     * Gets the value of the taxationFactors property.
     * 
     * @return
     *     possible object is
     *     {@link TaxationFactors }
     *     
     */
    public TaxationFactors getTaxationFactors() {
        return taxationFactors;
    }

    /**
     * Sets the value of the taxationFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxationFactors }
     *     
     */
    public void setTaxationFactors(TaxationFactors value) {
        this.taxationFactors = value;
    }

    /**
     * Gets the value of the tribalFactors property.
     * 
     * @return
     *     possible object is
     *     {@link TribalFactors }
     *     
     */
    public TribalFactors getTribalFactors() {
        return tribalFactors;
    }

    /**
     * Sets the value of the tribalFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TribalFactors }
     *     
     */
    public void setTribalFactors(TribalFactors value) {
        this.tribalFactors = value;
    }

    /**
     * Gets the value of the unpaidMedicalBillsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnpaidMedicalBillsIndicator() {
        return unpaidMedicalBillsIndicator;
    }

    /**
     * Sets the value of the unpaidMedicalBillsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnpaidMedicalBillsIndicator(Boolean value) {
        this.unpaidMedicalBillsIndicator = value;
    }

    /**
     * Gets the value of the usEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarDay }
     *     
     */
    public CalendarDay getUsEntryDate() {
        return usEntryDate;
    }

    /**
     * Sets the value of the usEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarDay }
     *     
     */
    public void setUsEntryDate(CalendarDay value) {
        this.usEntryDate = value;
    }

    /**
     * Gets the value of the uscisNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUscisNumber() {
        return uscisNumber;
    }

    /**
     * Sets the value of the uscisNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUscisNumber(String value) {
        this.uscisNumber = value;
    }

    /**
     * Gets the value of the usesMoreMedicalCareThanUsual property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesMoreMedicalCareThanUsual() {
        return usesMoreMedicalCareThanUsual;
    }

    /**
     * Sets the value of the usesMoreMedicalCareThanUsual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesMoreMedicalCareThanUsual(Boolean value) {
        this.usesMoreMedicalCareThanUsual = value;
    }

    /**
     * Gets the value of the veteranStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVeteranStatus() {
        return veteranStatus;
    }

    /**
     * Sets the value of the veteranStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVeteranStatus(Boolean value) {
        this.veteranStatus = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhone(String value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="applicantEmployer" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantEmployer" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicantEmployer"
    })
    public static class ApplicantEmployers {

        protected List<ApplicantEmployer> applicantEmployer;

        /**
         * Gets the value of the applicantEmployer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicantEmployer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicantEmployer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicantEmployer }
         * 
         * 
         */
        public List<ApplicantEmployer> getApplicantEmployer() {
            if (applicantEmployer == null) {
                applicantEmployer = new ArrayList<ApplicantEmployer>();
            }
            return this.applicantEmployer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="applicantExpense" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantExpense" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicantExpense"
    })
    public static class ApplicantExpenses {

        protected List<ApplicantExpense> applicantExpense;

        /**
         * Gets the value of the applicantExpense property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicantExpense property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicantExpense().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicantExpense }
         * 
         * 
         */
        public List<ApplicantExpense> getApplicantExpense() {
            if (applicantExpense == null) {
                applicantExpense = new ArrayList<ApplicantExpense>();
            }
            return this.applicantExpense;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="applicantIncome" type="{http://services.vida.psi.com/ClientManagement/1.0}applicantIncome" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicantIncome"
    })
    public static class ApplicantIncomes {

        protected List<ApplicantIncome> applicantIncome;

        /**
         * Gets the value of the applicantIncome property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicantIncome property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicantIncome().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ApplicantIncome }
         * 
         * 
         */
        public List<ApplicantIncome> getApplicantIncome() {
            if (applicantIncome == null) {
                applicantIncome = new ArrayList<ApplicantIncome>();
            }
            return this.applicantIncome;
        }

    }

}
