//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.15 at 05:33:55 PM CST 
//


package com.psi.vida.services.clientmanagement._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authorizedRepresentative complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorizedRepresentative"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="authorizedRepresentativeDesignatedDate" type="{http://services.vida.psi.com/ClientManagement/1.0}calendarDay" minOccurs="0"/&gt;
 *         &lt;element name="authorizedRepresentativeFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedRepresentativeOrganizationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedRepresentativeOrganizationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authorizedRepresentativePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="state" type="{http://services.vida.psi.com/ClientManagement/1.0}stateEnum" minOccurs="0"/&gt;
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorizedRepresentative", propOrder = {
    "authorizedRepresentativeDesignatedDate",
    "authorizedRepresentativeFullName",
    "authorizedRepresentativeOrganizationId",
    "authorizedRepresentativeOrganizationName",
    "authorizedRepresentativePhoneNumber",
    "city",
    "state",
    "street",
    "zipCode"
})
public class AuthorizedRepresentative {

    protected CalendarDay authorizedRepresentativeDesignatedDate;
    protected String authorizedRepresentativeFullName;
    protected String authorizedRepresentativeOrganizationId;
    protected String authorizedRepresentativeOrganizationName;
    protected String authorizedRepresentativePhoneNumber;
    protected String city;
    @XmlSchemaType(name = "string")
    protected StateEnum state;
    protected String street;
    protected String zipCode;

    /**
     * Gets the value of the authorizedRepresentativeDesignatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarDay }
     *     
     */
    public CalendarDay getAuthorizedRepresentativeDesignatedDate() {
        return authorizedRepresentativeDesignatedDate;
    }

    /**
     * Sets the value of the authorizedRepresentativeDesignatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarDay }
     *     
     */
    public void setAuthorizedRepresentativeDesignatedDate(CalendarDay value) {
        this.authorizedRepresentativeDesignatedDate = value;
    }

    /**
     * Gets the value of the authorizedRepresentativeFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedRepresentativeFullName() {
        return authorizedRepresentativeFullName;
    }

    /**
     * Sets the value of the authorizedRepresentativeFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedRepresentativeFullName(String value) {
        this.authorizedRepresentativeFullName = value;
    }

    /**
     * Gets the value of the authorizedRepresentativeOrganizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedRepresentativeOrganizationId() {
        return authorizedRepresentativeOrganizationId;
    }

    /**
     * Sets the value of the authorizedRepresentativeOrganizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedRepresentativeOrganizationId(String value) {
        this.authorizedRepresentativeOrganizationId = value;
    }

    /**
     * Gets the value of the authorizedRepresentativeOrganizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedRepresentativeOrganizationName() {
        return authorizedRepresentativeOrganizationName;
    }

    /**
     * Sets the value of the authorizedRepresentativeOrganizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedRepresentativeOrganizationName(String value) {
        this.authorizedRepresentativeOrganizationName = value;
    }

    /**
     * Gets the value of the authorizedRepresentativePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedRepresentativePhoneNumber() {
        return authorizedRepresentativePhoneNumber;
    }

    /**
     * Sets the value of the authorizedRepresentativePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedRepresentativePhoneNumber(String value) {
        this.authorizedRepresentativePhoneNumber = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateEnum }
     *     
     */
    public StateEnum getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateEnum }
     *     
     */
    public void setState(StateEnum value) {
        this.state = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

}
