//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.04 at 04:10:47 PM CST 
//


package com.psi.vida.services.clientmanagement._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contactSourceEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contactSourceEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CALL_IN"/&gt;
 *     &lt;enumeration value="DOC_IN"/&gt;
 *     &lt;enumeration value="CALL_OUT"/&gt;
 *     &lt;enumeration value="EMAIL_IN"/&gt;
 *     &lt;enumeration value="CHAT"/&gt;
 *     &lt;enumeration value="SOCIAL_MEDIA"/&gt;
 *     &lt;enumeration value="RESEARCH"/&gt;
 *     &lt;enumeration value="PHONE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "contactSourceEnum")
@XmlEnum
public enum ContactSourceEnum {

    CALL_IN,
    DOC_IN,
    CALL_OUT,
    EMAIL_IN,
    CHAT,
    SOCIAL_MEDIA,
    RESEARCH,
    PHONE;

    public String value() {
        return name();
    }

    public static ContactSourceEnum fromValue(String v) {
        return valueOf(v);
    }

}
