//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.09 at 12:57:55 PM CST 
//


package com.psi.vida.services.clientmanagement._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipToPersonEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="relationshipToPersonEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SPOUSE"/&gt;
 *     &lt;enumeration value="PARENT"/&gt;
 *     &lt;enumeration value="CHILD"/&gt;
 *     &lt;enumeration value="ADOPTED_CHILD"/&gt;
 *     &lt;enumeration value="FOSTER_CHILD"/&gt;
 *     &lt;enumeration value="GRANDPARENT"/&gt;
 *     &lt;enumeration value="GRANDCHILD"/&gt;
 *     &lt;enumeration value="UNCLE_OR_AUNT"/&gt;
 *     &lt;enumeration value="NEPHEW_OR_NIECE"/&gt;
 *     &lt;enumeration value="FIRST_COUSIN"/&gt;
 *     &lt;enumeration value="SON_IN_LAW_OR_DAUGHTER_IN_LAW"/&gt;
 *     &lt;enumeration value="BROTHER_IN_LAW_OR_SISTER_IN_LAW"/&gt;
 *     &lt;enumeration value="MOTHER_IN_LAW_OR_FATHER_IN_LAW"/&gt;
 *     &lt;enumeration value="SIBLING"/&gt;
 *     &lt;enumeration value="UNSPECIFIED_RELATIONSHIP"/&gt;
 *     &lt;enumeration value="WARD"/&gt;
 *     &lt;enumeration value="STEPPARENT"/&gt;
 *     &lt;enumeration value="STEPCHILD"/&gt;
 *     &lt;enumeration value="SPONSORED_DEPENDENT"/&gt;
 *     &lt;enumeration value="DEPENDENT_OF_MINOR_DEPENDENT"/&gt;
 *     &lt;enumeration value="FORMER_SPOUSE"/&gt;
 *     &lt;enumeration value="GUARDIAN"/&gt;
 *     &lt;enumeration value="COURT_APPOINTED_GUARDIAN"/&gt;
 *     &lt;enumeration value="COLLATERAL_DEPENDENT"/&gt;
 *     &lt;enumeration value="CHILD_OF_DOMESTIC_PARTNER"/&gt;
 *     &lt;enumeration value="PARENTS_DOMESTIC_PARTNER"/&gt;
 *     &lt;enumeration value="UNSPECIFIED_RELATIVE"/&gt;
 *     &lt;enumeration value="DOMESTIC_PARTNER"/&gt;
 *     &lt;enumeration value="ANNUITANT"/&gt;
 *     &lt;enumeration value="TRUSTEE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "relationshipToPersonEnum")
@XmlEnum
public enum RelationshipToPersonEnum {

    SPOUSE,
    PARENT,
    CHILD,
    ADOPTED_CHILD,
    FOSTER_CHILD,
    GRANDPARENT,
    GRANDCHILD,
    UNCLE_OR_AUNT,
    NEPHEW_OR_NIECE,
    FIRST_COUSIN,
    SON_IN_LAW_OR_DAUGHTER_IN_LAW,
    BROTHER_IN_LAW_OR_SISTER_IN_LAW,
    MOTHER_IN_LAW_OR_FATHER_IN_LAW,
    SIBLING,
    UNSPECIFIED_RELATIONSHIP,
    WARD,
    STEPPARENT,
    STEPCHILD,
    SPONSORED_DEPENDENT,
    DEPENDENT_OF_MINOR_DEPENDENT,
    FORMER_SPOUSE,
    GUARDIAN,
    COURT_APPOINTED_GUARDIAN,
    COLLATERAL_DEPENDENT,
    CHILD_OF_DOMESTIC_PARTNER,
    PARENTS_DOMESTIC_PARTNER,
    UNSPECIFIED_RELATIVE,
    DOMESTIC_PARTNER,
    ANNUITANT,
    TRUSTEE;

    public String value() {
        return name();
    }

    public static RelationshipToPersonEnum fromValue(String v) {
        return valueOf(v);
    }

}
