<wsdl:definitions
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:sch="http://www.maximus.com/customerdetails/sambha"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.maximus.com/customerdetails/sambha"
	targetNamespace="http://www.maximus.com/customerdetails/sambha">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified"
			targetNamespace="http://www.maximus.com/customerdetails/sambha">
			<xsd:element name="XmlRequest">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="XmlRequest" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="XmlResponse">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="XmlResponse" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="XmlResponse">
		<wsdl:part element="tns:XmlResponse" name="XmlResponse">
		</wsdl:part>
	</wsdl:message>
	<wsdl:message name="XmlRequest">
		<wsdl:part element="tns:XmlRequest" name="XmlRequest">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="PersonDetailsindicator">
		<wsdl:operation name="Xml">
			<wsdl:input message="tns:XmlRequest" name="XmlRequest">
			</wsdl:input>
			<wsdl:output message="tns:XmlResponse" name="XmlResponse">
			</wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PersonDetailsindicatorSoap11"
		type="tns:PersonDetailsindicator">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="Xml">
			<soap:operation soapAction="" />
			<wsdl:input name="XmlRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="XmlResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PersonDetailsindicatorService">
		<wsdl:port binding="tns:PersonDetailsindicatorSoap11"
			name="PersonDetailsindicatorSoap11">
			<soap:address location="http://localhost:9090/ws" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>