//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.15 at 05:33:54 PM CST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enrolledHealthPlan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="enrolledHealthPlan"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="coverageMonth" type="{http://services.vida.psi.com/ServiceClient/1.0}calendarMonth"/&gt;
 *         &lt;element name="enrollmentDisplayStatus" type="{http://services.vida.psi.com/ServiceClient/1.0}enrollmentDisplayStatusEnum"/&gt;
 *         &lt;element name="medicalEnrollmentStatus" type="{http://services.vida.psi.com/ServiceClient/1.0}externalEnrollmentStatusEnum"/&gt;
 *         &lt;element name="dentalPlan" type="{http://services.vida.psi.com/ServiceClient/1.0}healthPlan" minOccurs="0"/&gt;
 *         &lt;element name="dentalPlanId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="medicalPlan" type="{http://services.vida.psi.com/ServiceClient/1.0}healthPlan" minOccurs="0"/&gt;
 *         &lt;element name="medicalPlanId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="programName" type="{http://services.vida.psi.com/ServiceClient/1.0}programTypeEnum" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enrolledHealthPlan", propOrder = {
    "coverageMonth",
    "enrollmentDisplayStatus",
    "medicalEnrollmentStatus",
    "dentalPlan",
    "dentalPlanId",
    "medicalPlan",
    "medicalPlanId",
    "programName"
})
public class EnrolledHealthPlan {

    @XmlElement(required = true)
    protected CalendarMonth coverageMonth;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected EnrollmentDisplayStatusEnum enrollmentDisplayStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ExternalEnrollmentStatusEnum medicalEnrollmentStatus;
    protected HealthPlan dentalPlan;
    protected Long dentalPlanId;
    protected HealthPlan medicalPlan;
    protected Long medicalPlanId;
    @XmlSchemaType(name = "string")
    protected ProgramTypeEnum programName;

    /**
     * Gets the value of the coverageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarMonth }
     *     
     */
    public CalendarMonth getCoverageMonth() {
        return coverageMonth;
    }

    /**
     * Sets the value of the coverageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarMonth }
     *     
     */
    public void setCoverageMonth(CalendarMonth value) {
        this.coverageMonth = value;
    }

    /**
     * Gets the value of the enrollmentDisplayStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentDisplayStatusEnum }
     *     
     */
    public EnrollmentDisplayStatusEnum getEnrollmentDisplayStatus() {
        return enrollmentDisplayStatus;
    }

    /**
     * Sets the value of the enrollmentDisplayStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentDisplayStatusEnum }
     *     
     */
    public void setEnrollmentDisplayStatus(EnrollmentDisplayStatusEnum value) {
        this.enrollmentDisplayStatus = value;
    }

    /**
     * Gets the value of the medicalEnrollmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalEnrollmentStatusEnum }
     *     
     */
    public ExternalEnrollmentStatusEnum getMedicalEnrollmentStatus() {
        return medicalEnrollmentStatus;
    }

    /**
     * Sets the value of the medicalEnrollmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalEnrollmentStatusEnum }
     *     
     */
    public void setMedicalEnrollmentStatus(ExternalEnrollmentStatusEnum value) {
        this.medicalEnrollmentStatus = value;
    }

    /**
     * Gets the value of the dentalPlan property.
     * 
     * @return
     *     possible object is
     *     {@link HealthPlan }
     *     
     */
    public HealthPlan getDentalPlan() {
        return dentalPlan;
    }

    /**
     * Sets the value of the dentalPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthPlan }
     *     
     */
    public void setDentalPlan(HealthPlan value) {
        this.dentalPlan = value;
    }

    /**
     * Gets the value of the dentalPlanId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDentalPlanId() {
        return dentalPlanId;
    }

    /**
     * Sets the value of the dentalPlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDentalPlanId(Long value) {
        this.dentalPlanId = value;
    }

    /**
     * Gets the value of the medicalPlan property.
     * 
     * @return
     *     possible object is
     *     {@link HealthPlan }
     *     
     */
    public HealthPlan getMedicalPlan() {
        return medicalPlan;
    }

    /**
     * Sets the value of the medicalPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthPlan }
     *     
     */
    public void setMedicalPlan(HealthPlan value) {
        this.medicalPlan = value;
    }

    /**
     * Gets the value of the medicalPlanId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMedicalPlanId() {
        return medicalPlanId;
    }

    /**
     * Sets the value of the medicalPlanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMedicalPlanId(Long value) {
        this.medicalPlanId = value;
    }

    /**
     * Gets the value of the programName property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramTypeEnum }
     *     
     */
    public ProgramTypeEnum getProgramName() {
        return programName;
    }

    /**
     * Sets the value of the programName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramTypeEnum }
     *     
     */
    public void setProgramName(ProgramTypeEnum value) {
        this.programName = value;
    }

}
