//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.09 at 03:15:58 PM IST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enrollmentStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enrollmentStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="APPROVED_MEDICAID"/>
 *     &lt;enumeration value="CANCELED_MEDICAID_NON_COMPLIANT"/>
 *     &lt;enumeration value="CANCELED_NON_COMPLIANT"/>
 *     &lt;enumeration value="CANCELED_NON_PAYMENT"/>
 *     &lt;enumeration value="CANCELED_ON_MEDICAID"/>
 *     &lt;enumeration value="CANCELED_OTHER"/>
 *     &lt;enumeration value="CANCELED_OUT_OF_HH"/>
 *     &lt;enumeration value="CANCELED_VIC_EXPIRED"/>
 *     &lt;enumeration value="DENIED_APP_EXPIRED"/>
 *     &lt;enumeration value="DENIED_CMS_OPT_OUT"/>
 *     &lt;enumeration value="DENIED_MDCD_OVER_INCOME"/>
 *     &lt;enumeration value="DENIED_OUT_OF_HH"/>
 *     &lt;enumeration value="DENIED_MEDICAID_NON_COMPLIANT"/>
 *     &lt;enumeration value="DENIED_NON_COMPLIANT"/>
 *     &lt;enumeration value="DENIED_NON_QUALIFIED"/>
 *     &lt;enumeration value="DENIED_OTHER_INS"/>
 *     &lt;enumeration value="DENIED_OVER_AGE"/>
 *     &lt;enumeration value="DENIED_ON_MEDICAID"/>
 *     &lt;enumeration value="DENIED_OUT_OF_STATE"/>
 *     &lt;enumeration value="DENIED_OTHER"/>
 *     &lt;enumeration value="ENROLLED"/>
 *     &lt;enumeration value="PENDING_ENROLLMENT"/>
 *     &lt;enumeration value="PENDING_MEDICAID_REFERRAL"/>
 *     &lt;enumeration value="PENDING_PREMIUM_PAYMENT"/>
 *     &lt;enumeration value="PENDING_VERIFICATIONS"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enrollmentStatusEnum")
@XmlEnum
public enum EnrollmentStatusEnum {

    APPROVED_MEDICAID,
    CANCELED_MEDICAID_NON_COMPLIANT,
    CANCELED_NON_COMPLIANT,
    CANCELED_NON_PAYMENT,
    CANCELED_ON_MEDICAID,
    CANCELED_OTHER,
    CANCELED_OUT_OF_HH,
    CANCELED_VIC_EXPIRED,
    DENIED_APP_EXPIRED,
    DENIED_CMS_OPT_OUT,
    DENIED_MDCD_OVER_INCOME,
    DENIED_OUT_OF_HH,
    DENIED_MEDICAID_NON_COMPLIANT,
    DENIED_NON_COMPLIANT,
    DENIED_NON_QUALIFIED,
    DENIED_OTHER_INS,
    DENIED_OVER_AGE,
    DENIED_ON_MEDICAID,
    DENIED_OUT_OF_STATE,
    DENIED_OTHER,
    ENROLLED,
    PENDING_ENROLLMENT,
    PENDING_MEDICAID_REFERRAL,
    PENDING_PREMIUM_PAYMENT,
    PENDING_VERIFICATIONS,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static EnrollmentStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
