//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.09 at 03:15:58 PM IST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalAccountMissingInfoEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="externalAccountMissingInfoEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MISSING_UNKNOWN"/>
 *     &lt;enumeration value="RESIDENCE_STATE_BLANK"/>
 *     &lt;enumeration value="RESIDENCE_COUNTY_BLANK"/>
 *     &lt;enumeration value="HOME_PHONE_BLANK"/>
 *     &lt;enumeration value="CELL_PHONE_BLANK"/>
 *     &lt;enumeration value="INCOME_UNVERIFIED"/>
 *     &lt;enumeration value="APPLICATION_NOT_SIGNED"/>
 *     &lt;enumeration value="INCOMPLETE_MAILING_ADDRESS"/>
 *     &lt;enumeration value="MISSING_EARNED_INCOME"/>
 *     &lt;enumeration value="MISSING_UNEARNED_INCOME"/>
 *     &lt;enumeration value="HOUSEHOLD_UNPAID_MEDICAL_BLANK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "externalAccountMissingInfoEnum")
@XmlEnum
public enum ExternalAccountMissingInfoEnum {

    MISSING_UNKNOWN,
    RESIDENCE_STATE_BLANK,
    RESIDENCE_COUNTY_BLANK,
    HOME_PHONE_BLANK,
    CELL_PHONE_BLANK,
    INCOME_UNVERIFIED,
    APPLICATION_NOT_SIGNED,
    INCOMPLETE_MAILING_ADDRESS,
    MISSING_EARNED_INCOME,
    MISSING_UNEARNED_INCOME,
    HOUSEHOLD_UNPAID_MEDICAL_BLANK;

    public String value() {
        return name();
    }

    public static ExternalAccountMissingInfoEnum fromValue(String v) {
        return valueOf(v);
    }

}
