//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.09 at 12:57:54 PM CST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalAccountMissingInfoEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="externalAccountMissingInfoEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MISSING_UNKNOWN"/&gt;
 *     &lt;enumeration value="RESIDENCE_STATE_BLANK"/&gt;
 *     &lt;enumeration value="RESIDENCE_COUNTY_BLANK"/&gt;
 *     &lt;enumeration value="HOME_PHONE_BLANK"/&gt;
 *     &lt;enumeration value="CELL_PHONE_BLANK"/&gt;
 *     &lt;enumeration value="INCOME_UNVERIFIED"/&gt;
 *     &lt;enumeration value="APPLICATION_NOT_SIGNED"/&gt;
 *     &lt;enumeration value="INCOMPLETE_MAILING_ADDRESS"/&gt;
 *     &lt;enumeration value="MISSING_EARNED_INCOME"/&gt;
 *     &lt;enumeration value="MISSING_UNEARNED_INCOME"/&gt;
 *     &lt;enumeration value="HOUSEHOLD_UNPAID_MEDICAL_BLANK"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "externalAccountMissingInfoEnum")
@XmlEnum
public enum ExternalAccountMissingInfoEnum {

    MISSING_UNKNOWN,
    RESIDENCE_STATE_BLANK,
    RESIDENCE_COUNTY_BLANK,
    HOME_PHONE_BLANK,
    CELL_PHONE_BLANK,
    INCOME_UNVERIFIED,
    APPLICATION_NOT_SIGNED,
    INCOMPLETE_MAILING_ADDRESS,
    MISSING_EARNED_INCOME,
    MISSING_UNEARNED_INCOME,
    HOUSEHOLD_UNPAID_MEDICAL_BLANK;

    public String value() {
        return name();
    }

    public static ExternalAccountMissingInfoEnum fromValue(String v) {
        return valueOf(v);
    }

}
