//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 11:47:15 AM CST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for externalMemberMissingInfoEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="externalMemberMissingInfoEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PARENT_ONE_FIRST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_ONE_LAST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_ONE_SSN_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_ONE_DOB_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_TWO_FIRST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_TWO_LAST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_TWO_SSN_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_TWO_DOB_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_DOB_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_GENDER_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_DECLARED_CITIZENSHIP_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_NONCITIZEN_UNVERIFIED"/&gt;
 *     &lt;enumeration value="CHILD_CITIZEN_UNVERIFIED"/&gt;
 *     &lt;enumeration value="CHILD_PARENT_ONE_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_PARENT_TWO_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_FIRST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_LAST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_PRESENCE_HOUSEHOLD_UNKNOWN"/&gt;
 *     &lt;enumeration value="CHILD_SSN_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_OTHER_INSURANCE_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_OTHER_INSURANCE_NAME_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_OTHER_INSURANCE_COST_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_VOL_CANC_INS_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_VOL_CANC_INS_DATE_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_TRIBAL_MMBRSHP_UNVERIFIED"/&gt;
 *     &lt;enumeration value="SIBLING_DATE_OF_BIRTH_BLANK"/&gt;
 *     &lt;enumeration value="SIBLING_PARENT_ONE_BLANK"/&gt;
 *     &lt;enumeration value="SIBLING_PARENT_TWO_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_OTHER_FIRST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_OTHER_LAST_NAME_BLANK"/&gt;
 *     &lt;enumeration value="PARENT_OTHER_SSN_BLANK"/&gt;
 *     &lt;enumeration value="SPECIAL_NEEDS_BLANK"/&gt;
 *     &lt;enumeration value="APPLYING_FOR_KIDCARE_BLANK"/&gt;
 *     &lt;enumeration value="CHILD_IDENTITY_UNVERIFIED"/&gt;
 *     &lt;enumeration value="CHILD_MDCD_REFERRAL_PENDING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "externalMemberMissingInfoEnum")
@XmlEnum
public enum ExternalMemberMissingInfoEnum {

    PARENT_ONE_FIRST_NAME_BLANK,
    PARENT_ONE_LAST_NAME_BLANK,
    PARENT_ONE_SSN_BLANK,
    PARENT_ONE_DOB_BLANK,
    PARENT_TWO_FIRST_NAME_BLANK,
    PARENT_TWO_LAST_NAME_BLANK,
    PARENT_TWO_SSN_BLANK,
    PARENT_TWO_DOB_BLANK,
    CHILD_DOB_BLANK,
    CHILD_GENDER_BLANK,
    CHILD_DECLARED_CITIZENSHIP_BLANK,
    CHILD_NONCITIZEN_UNVERIFIED,
    CHILD_CITIZEN_UNVERIFIED,
    CHILD_PARENT_ONE_BLANK,
    CHILD_PARENT_TWO_BLANK,
    CHILD_FIRST_NAME_BLANK,
    CHILD_LAST_NAME_BLANK,
    CHILD_PRESENCE_HOUSEHOLD_UNKNOWN,
    CHILD_SSN_BLANK,
    CHILD_OTHER_INSURANCE_BLANK,
    CHILD_OTHER_INSURANCE_NAME_BLANK,
    CHILD_OTHER_INSURANCE_COST_BLANK,
    CHILD_VOL_CANC_INS_BLANK,
    CHILD_VOL_CANC_INS_DATE_BLANK,
    CHILD_TRIBAL_MMBRSHP_UNVERIFIED,
    SIBLING_DATE_OF_BIRTH_BLANK,
    SIBLING_PARENT_ONE_BLANK,
    SIBLING_PARENT_TWO_BLANK,
    PARENT_OTHER_FIRST_NAME_BLANK,
    PARENT_OTHER_LAST_NAME_BLANK,
    PARENT_OTHER_SSN_BLANK,
    SPECIAL_NEEDS_BLANK,
    APPLYING_FOR_KIDCARE_BLANK,
    CHILD_IDENTITY_UNVERIFIED,
    CHILD_MDCD_REFERRAL_PENDING;

    public String value() {
        return name();
    }

    public static ExternalMemberMissingInfoEnum fromValue(String v) {
        return valueOf(v);
    }

}
