//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.04 at 04:10:46 PM CST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for incomeMissingInfoEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="incomeMissingInfoEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INCOMPLETE_EARNED_INCOME_NAME"/&gt;
 *     &lt;enumeration value="INCOMPLETE_EARNED_INCOME_AMOUNT"/&gt;
 *     &lt;enumeration value="INCOMPLETE_CHILD_SUPPORT_INCOME_NAME"/&gt;
 *     &lt;enumeration value="INCOMPLETE_UNEARNED_INCOME_NAME"/&gt;
 *     &lt;enumeration value="INCOMPLETE_UNEARNED_INCOME_AMOUNT"/&gt;
 *     &lt;enumeration value="PROOF_OF_EARNED_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_SELF_EMPLOYMENT_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_UNEARNED_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_CHILD_SUPPORT_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_SSA_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_SSI_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_UNEMPLOYMENT_INCOME"/&gt;
 *     &lt;enumeration value="PROOF_OF_OTHER_INCOME"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "incomeMissingInfoEnum")
@XmlEnum
public enum IncomeMissingInfoEnum {

    INCOMPLETE_EARNED_INCOME_NAME,
    INCOMPLETE_EARNED_INCOME_AMOUNT,
    INCOMPLETE_CHILD_SUPPORT_INCOME_NAME,
    INCOMPLETE_UNEARNED_INCOME_NAME,
    INCOMPLETE_UNEARNED_INCOME_AMOUNT,
    PROOF_OF_EARNED_INCOME,
    PROOF_OF_SELF_EMPLOYMENT_INCOME,
    PROOF_OF_UNEARNED_INCOME,
    PROOF_OF_CHILD_SUPPORT_INCOME,
    PROOF_OF_SSA_INCOME,
    PROOF_OF_SSI_INCOME,
    PROOF_OF_UNEMPLOYMENT_INCOME,
    PROOF_OF_OTHER_INCOME;

    public String value() {
        return name();
    }

    public static IncomeMissingInfoEnum fromValue(String v) {
        return valueOf(v);
    }

}
