//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.09 at 03:15:58 PM IST 
//


package com.psi.vida.services.serviceclient._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.psi.vida.services.serviceclient._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IsAliveResponse_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "isAliveResponse");
    private final static QName _AccountData_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "accountData");
    private final static QName _UpdateAccountResponse_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "updateAccountResponse");
    private final static QName _ViewAccountData_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "viewAccountData");
    private final static QName _IsAlive_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "isAlive");
    private final static QName _ViewAccountDataResponse_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "viewAccountDataResponse");
    private final static QName _UpdateAccount_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "updateAccount");
    private final static QName _UpdateAccountData_QNAME = new QName("http://services.vida.psi.com/ServiceClient/1.0", "updateAccountData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.psi.vida.services.serviceclient._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServerStatusResponse }
     * 
     */
    public ServerStatusResponse createServerStatusResponse() {
        return new ServerStatusResponse();
    }

    /**
     * Create an instance of {@link Member }
     * 
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link AccountData }
     * 
     */
    public AccountData createAccountData() {
        return new AccountData();
    }

    /**
     * Create an instance of {@link UpdateAccountData }
     * 
     */
    public UpdateAccountData createUpdateAccountData() {
        return new UpdateAccountData();
    }

    /**
     * Create an instance of {@link ViewAccountData }
     * 
     */
    public ViewAccountData createViewAccountData() {
        return new ViewAccountData();
    }

    /**
     * Create an instance of {@link UpdateAccountResponse }
     * 
     */
    public UpdateAccountResponse createUpdateAccountResponse() {
        return new UpdateAccountResponse();
    }

    /**
     * Create an instance of {@link IsAlive }
     * 
     */
    public IsAlive createIsAlive() {
        return new IsAlive();
    }

    /**
     * Create an instance of {@link IsAliveResponse }
     * 
     */
    public IsAliveResponse createIsAliveResponse() {
        return new IsAliveResponse();
    }

    /**
     * Create an instance of {@link ViewAccountDataResponse }
     * 
     */
    public ViewAccountDataResponse createViewAccountDataResponse() {
        return new ViewAccountDataResponse();
    }

    /**
     * Create an instance of {@link UpdateAccount }
     * 
     */
    public UpdateAccount createUpdateAccount() {
        return new UpdateAccount();
    }

    /**
     * Create an instance of {@link AccountContactInfo }
     * 
     */
    public AccountContactInfo createAccountContactInfo() {
        return new AccountContactInfo();
    }

    /**
     * Create an instance of {@link ImmigrationFactors }
     * 
     */
    public ImmigrationFactors createImmigrationFactors() {
        return new ImmigrationFactors();
    }

    /**
     * Create an instance of {@link EnrolledHealthPlan }
     * 
     */
    public EnrolledHealthPlan createEnrolledHealthPlan() {
        return new EnrolledHealthPlan();
    }

    /**
     * Create an instance of {@link IdentityFactors }
     * 
     */
    public IdentityFactors createIdentityFactors() {
        return new IdentityFactors();
    }

    /**
     * Create an instance of {@link LetterRequest }
     * 
     */
    public LetterRequest createLetterRequest() {
        return new LetterRequest();
    }

    /**
     * Create an instance of {@link EmploymentFactors }
     * 
     */
    public EmploymentFactors createEmploymentFactors() {
        return new EmploymentFactors();
    }

    /**
     * Create an instance of {@link HealthPlanChangeRequest }
     * 
     */
    public HealthPlanChangeRequest createHealthPlanChangeRequest() {
        return new HealthPlanChangeRequest();
    }

    /**
     * Create an instance of {@link Confirmation }
     * 
     */
    public Confirmation createConfirmation() {
        return new Confirmation();
    }

    /**
     * Create an instance of {@link Expense }
     * 
     */
    public Expense createExpense() {
        return new Expense();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link HealthPlan }
     * 
     */
    public HealthPlan createHealthPlan() {
        return new HealthPlan();
    }

    /**
     * Create an instance of {@link Income }
     * 
     */
    public Income createIncome() {
        return new Income();
    }

    /**
     * Create an instance of {@link TribalFactors }
     * 
     */
    public TribalFactors createTribalFactors() {
        return new TribalFactors();
    }

    /**
     * Create an instance of {@link CalendarMonth }
     * 
     */
    public CalendarMonth createCalendarMonth() {
        return new CalendarMonth();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link CalendarDay }
     * 
     */
    public CalendarDay createCalendarDay() {
        return new CalendarDay();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link CitizenshipFactors }
     * 
     */
    public CitizenshipFactors createCitizenshipFactors() {
        return new CitizenshipFactors();
    }

    /**
     * Create an instance of {@link AccountMembership }
     * 
     */
    public AccountMembership createAccountMembership() {
        return new AccountMembership();
    }

    /**
     * Create an instance of {@link InsuranceProvider }
     * 
     */
    public InsuranceProvider createInsuranceProvider() {
        return new InsuranceProvider();
    }

    /**
     * Create an instance of {@link TaxationFactors }
     * 
     */
    public TaxationFactors createTaxationFactors() {
        return new TaxationFactors();
    }

    /**
     * Create an instance of {@link PaymentInfo }
     * 
     */
    public PaymentInfo createPaymentInfo() {
        return new PaymentInfo();
    }

    /**
     * Create an instance of {@link ServerStatusResponse.ServerStatuses }
     * 
     */
    public ServerStatusResponse.ServerStatuses createServerStatusResponseServerStatuses() {
        return new ServerStatusResponse.ServerStatuses();
    }

    /**
     * Create an instance of {@link Member.AvailableDentalPlans }
     * 
     */
    public Member.AvailableDentalPlans createMemberAvailableDentalPlans() {
        return new Member.AvailableDentalPlans();
    }

    /**
     * Create an instance of {@link Member.AvailableHealthPlans }
     * 
     */
    public Member.AvailableHealthPlans createMemberAvailableHealthPlans() {
        return new Member.AvailableHealthPlans();
    }

    /**
     * Create an instance of {@link Member.ExpenseMissingInfoItems }
     * 
     */
    public Member.ExpenseMissingInfoItems createMemberExpenseMissingInfoItems() {
        return new Member.ExpenseMissingInfoItems();
    }

    /**
     * Create an instance of {@link Member.Expenses }
     * 
     */
    public Member.Expenses createMemberExpenses() {
        return new Member.Expenses();
    }

    /**
     * Create an instance of {@link Member.IncomeMissingInfoItems }
     * 
     */
    public Member.IncomeMissingInfoItems createMemberIncomeMissingInfoItems() {
        return new Member.IncomeMissingInfoItems();
    }

    /**
     * Create an instance of {@link Member.Incomes }
     * 
     */
    public Member.Incomes createMemberIncomes() {
        return new Member.Incomes();
    }

    /**
     * Create an instance of {@link Member.MemberMissingInfoItems }
     * 
     */
    public Member.MemberMissingInfoItems createMemberMemberMissingInfoItems() {
        return new Member.MemberMissingInfoItems();
    }

    /**
     * Create an instance of {@link AccountData.AccountMissingInfoItems }
     * 
     */
    public AccountData.AccountMissingInfoItems createAccountDataAccountMissingInfoItems() {
        return new AccountData.AccountMissingInfoItems();
    }

    /**
     * Create an instance of {@link AccountData.Members }
     * 
     */
    public AccountData.Members createAccountDataMembers() {
        return new AccountData.Members();
    }

    /**
     * Create an instance of {@link AccountData.Letters }
     * 
     */
    public AccountData.Letters createAccountDataLetters() {
        return new AccountData.Letters();
    }

    /**
     * Create an instance of {@link UpdateAccountData.Members }
     * 
     */
    public UpdateAccountData.Members createUpdateAccountDataMembers() {
        return new UpdateAccountData.Members();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsAliveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "isAliveResponse")
    public JAXBElement<IsAliveResponse> createIsAliveResponse(IsAliveResponse value) {
        return new JAXBElement<IsAliveResponse>(_IsAliveResponse_QNAME, IsAliveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "accountData")
    public JAXBElement<AccountData> createAccountData(AccountData value) {
        return new JAXBElement<AccountData>(_AccountData_QNAME, AccountData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "updateAccountResponse")
    public JAXBElement<UpdateAccountResponse> createUpdateAccountResponse(UpdateAccountResponse value) {
        return new JAXBElement<UpdateAccountResponse>(_UpdateAccountResponse_QNAME, UpdateAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewAccountData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "viewAccountData")
    public JAXBElement<ViewAccountData> createViewAccountData(ViewAccountData value) {
        return new JAXBElement<ViewAccountData>(_ViewAccountData_QNAME, ViewAccountData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsAlive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "isAlive")
    public JAXBElement<IsAlive> createIsAlive(IsAlive value) {
        return new JAXBElement<IsAlive>(_IsAlive_QNAME, IsAlive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewAccountDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "viewAccountDataResponse")
    public JAXBElement<ViewAccountDataResponse> createViewAccountDataResponse(ViewAccountDataResponse value) {
        return new JAXBElement<ViewAccountDataResponse>(_ViewAccountDataResponse_QNAME, ViewAccountDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "updateAccount")
    public JAXBElement<UpdateAccount> createUpdateAccount(UpdateAccount value) {
        return new JAXBElement<UpdateAccount>(_UpdateAccount_QNAME, UpdateAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAccountData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/ServiceClient/1.0", name = "updateAccountData")
    public JAXBElement<UpdateAccountData> createUpdateAccountData(UpdateAccountData value) {
        return new JAXBElement<UpdateAccountData>(_UpdateAccountData_QNAME, UpdateAccountData.class, null, value);
    }

}
