//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.15 at 05:33:54 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.vida.psi.com/ServiceClient/1.0")
package com.psi.vida.services.serviceclient._1;
