//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.15 at 05:33:56 PM CST 
//


package com.psi.vida.services.documentservices._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inboundDocumentServiceReply complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inboundDocumentServiceReply"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceReplyStatus" type="{http://services.vida.psi.com/DocumentServices/1.0}serviceReplyEnum" minOccurs="0"/&gt;
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inboundDocumentServiceReply", propOrder = {
    "serviceReplyStatus",
    "message"
})
public class InboundDocumentServiceReply {

    @XmlSchemaType(name = "string")
    protected ServiceReplyEnum serviceReplyStatus;
    protected String message;

    /**
     * Gets the value of the serviceReplyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceReplyEnum }
     *     
     */
    public ServiceReplyEnum getServiceReplyStatus() {
        return serviceReplyStatus;
    }

    /**
     * Sets the value of the serviceReplyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceReplyEnum }
     *     
     */
    public void setServiceReplyStatus(ServiceReplyEnum value) {
        this.serviceReplyStatus = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
