//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 11:47:14 AM CST 
//


package com.psi.vida.services.lettermanagement._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.psi.vida.services.lettermanagement._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InsertLetterPDFLinksResponse_QNAME = new QName("http://services.vida.psi.com/LetterManagement/1.0", "insertLetterPDFLinksResponse");
    private final static QName _InsertLetterPDFLinks_QNAME = new QName("http://services.vida.psi.com/LetterManagement/1.0", "insertLetterPDFLinks");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.psi.vida.services.lettermanagement._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertLetterPDFLinksResponse }
     * 
     */
    public InsertLetterPDFLinksResponse createInsertLetterPDFLinksResponse() {
        return new InsertLetterPDFLinksResponse();
    }

    /**
     * Create an instance of {@link InsertLetterPDFLinks }
     * 
     */
    public InsertLetterPDFLinks createInsertLetterPDFLinks() {
        return new InsertLetterPDFLinks();
    }

    /**
     * Create an instance of {@link Confirmation }
     * 
     */
    public Confirmation createConfirmation() {
        return new Confirmation();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertLetterPDFLinksResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/LetterManagement/1.0", name = "insertLetterPDFLinksResponse")
    public JAXBElement<InsertLetterPDFLinksResponse> createInsertLetterPDFLinksResponse(InsertLetterPDFLinksResponse value) {
        return new JAXBElement<InsertLetterPDFLinksResponse>(_InsertLetterPDFLinksResponse_QNAME, InsertLetterPDFLinksResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InsertLetterPDFLinks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.vida.psi.com/LetterManagement/1.0", name = "insertLetterPDFLinks")
    public JAXBElement<InsertLetterPDFLinks> createInsertLetterPDFLinks(InsertLetterPDFLinks value) {
        return new JAXBElement<InsertLetterPDFLinks>(_InsertLetterPDFLinks_QNAME, InsertLetterPDFLinks.class, null, value);
    }

}
