server:
  port: 8080
xslt:
  request: pdfLinkRequest.xslt
  response: pdfLinkResponse.xslt
  
spring:
  profiles:
    active: ${SPRING_PROFILE:development}

email:
  smtpServer:  smtpint.maxcorp.maximus
  port:  25
  fromAddress:  OSB@Policy-Studies.com
  replyToAddress:  doNotReply@Policy-Studies.com
  toAddress:  52243@maximus.com
  
---
spring:  profiles: development
  cache:
    type: simple
  
  activemq:    in-memory: true
 
vida:
  letterWSServiceEndpoint: http://flcsvc01qf3.corp.psi:5001/LettersManagement/LetterManagerWSService
  loggerWSServiceEndpoint: http://flcsvc01qf3.corp.psi:5001/commonServices/VidaWSLoggerWS        
  documentWSServiceEndpoint: http://flcsvc01qf3.corp.psi:5001/inboundDocManagement/InboundDocManagerWS
  clientManagWSServiceEndPoint: http://flcsvc01qf3.corp.psi:5001/accountManagement/ClientManagementWS
  atmAccountTransferEndPoint:  http://flcatmtc01qf3.corp.psi:8080/flAtm/service/fhkAccountTransfer
  
---
spring:
  profiles: production
  cache:
    type: redis
  
  activemq:
    in-memory: true
  
vida:
  letterWSServiceEndpoint: http://flcsvc01qf3.corp.psi:900/LettersManagement/LetterManagerWSService   
  loggerWSServiceEndpoint: http://flcsvc01qf3.corp.psi:900/commonServices/VidaWSLoggerWS   
  documentWSServiceEndpoint: http://flcsvc01qf3.corp.psi:900/inboundDocManagement/InboundDocManagerWS
  clientManagWSServiceEndPoint: http://flcsvc01qf3.corp.psi:900/accountManagement/ClientManagementWS
  atmAccountTransferEndPoint:  http://flcatmtc01qf3.corp.psi:8080/flAtm/service/fhkAccountTransfer        