FROM amazoncorretto:11

MAINTAINER Daniel Yang <danielyang@maximus.com>

RUN mkdir -p /u01 && \
    chmod 777 /u01
    
RUN mkdir -p /u01/data && \
    chmod 777 /u01/data    

#VOLUME /u01/data

COPY target/soap-ws-xquery-transformationNikant-0.0.1-SNAPSHOT.jar /u01/

WORKDIR /u01

EXPOSE 8080

CMD ["java", "-jar", "soap-ws-xquery-transformationNikant-0.0.1-SNAPSHOT.jar"] 

